[package]
name = "chunksearch"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
log = "0.4.20"
simple_logger = "4.2.0"
clap = { version="4.4.2", features = ["cargo"]}

[profile.release]
debug = true
